#pragma once

enum PlayerState
{
    PLAYER_STATE_SMALL,
    PLAYER_STATE_BIG,
    PLAYER_STATE_FIRE,

    PLAYER_STATE_TRANSFORMING_SMALL_TO_BIG,
    PLAYER_STATE_TRANSFORMING_BIG_TO_SMALL,
    PLAYER_STATE_TRANSFORMING_BIG_TO_FIRE,
    PLAYER_STATE_TRANSFORMING_FIRE_TO_BIG,
    PLAYER_STATE_TRANSFORMING_SMALL_TO_FIRE
};